
using GitCatalog.Core;
using GitCatalog.Generation;
using GitCatalog.Governance;
using GitCatalog.Import;
using GitCatalog.Serialization;
using GitCatalog.Validation;

namespace GitCatalog.Tests;

public class CatalogTests
{
    [Fact]
    public void Load_Reads_Table_Metadata_From_Yaml()
    {
        var root = CreateTempRepoWithCatalog(
            "sales.order.yaml",
            """
            id: sales.order
            database: sales
            schema: dbo
            description: Customer order table
            owner:
              team: Commercial Systems
            columns:
              - name: OrderId
                type: bigint
                pk: true
                description: Primary key
            """);

        var result = CatalogLoader.Load(root);

        Assert.Empty(result.Diagnostics);
        var table = Assert.Single(result.Tables);
        Assert.Equal("sales.order", table.Id);
        Assert.Equal("Commercial Systems", table.Owner.Team);
        var column = Assert.Single(table.Columns);
        Assert.True(column.Pk);
    }

    [Fact]
    public void Validate_Flags_Missing_Required_Fields()
    {
        var issues = CatalogValidator.Validate(
            [
                new TableDefinition
                {
                    Id = "sales.order",
                    Database = "sales",
                    Schema = "dbo",
                    Description = "",
                    Columns = [new ColumnDefinition { Name = "", Type = "" }]
                }
            ]).ToList();

        Assert.Contains(issues, x => x.Contains("Description is required"));
        Assert.Contains(issues, x => x.Contains("Column name is required"));
        Assert.Contains(issues, x => x.Contains("Column type is required"));
    }

    [Fact]
    public void Validate_Flags_Duplicate_Columns_And_Invalid_Foreign_Keys()
    {
        var issues = CatalogValidator.Validate(
            [
                new TableDefinition
                {
                    Id = "sales.order",
                    Database = "sales",
                    Schema = "dbo",
                    Description = "Order table for testing",
                    Columns =
                    [
                        new ColumnDefinition { Name = "OrderId", Type = "bigint", Pk = true },
                        new ColumnDefinition { Name = "OrderId", Type = "bigint" },
                        new ColumnDefinition { Name = "CustomerId", Type = "bigint", Fk = "badformat" },
                        new ColumnDefinition { Name = "RegionId", Type = "bigint", Fk = "sales.region.RegionId" }
                    ]
                },
                new TableDefinition
                {
                    Id = "sales.customer",
                    Database = "sales",
                    Schema = "dbo",
                    Description = "Customer table for testing",
                    Columns = [new ColumnDefinition { Name = "CustomerId", Type = "bigint", Pk = true }]
                }
            ]).ToList();

        Assert.Contains(issues, x => x.Contains("Duplicate column name 'OrderId'"));
        Assert.Contains(issues, x => x.Contains("Invalid foreign key format 'badformat'"));
        Assert.Contains(issues, x => x.Contains("Foreign key target table 'sales.region' not found"));
    }

    [Fact]
    public void Lint_Flags_Missing_Owner_And_Column_Descriptions()
    {
        var warnings = GovernanceEngine.Lint(
            [
                new TableDefinition
                {
                    Id = "sales.order",
                    Database = "sales",
                    Schema = "dbo",
                    Description = "short",
                    Owner = new OwnerDefinition { Team = "" },
                    Columns = [new ColumnDefinition { Name = "OrderId", Type = "bigint", Description = "" }]
                }
            ]).ToList();

        Assert.Contains(warnings, x => x.Contains("Missing owner team"));
        Assert.Contains(warnings, x => x.Contains("Description is too short"));
        Assert.Contains(warnings, x => x.Contains("Missing description for column"));
    }

    [Fact]
    public void Lint_Flags_AutoGenerated_Description_And_Missing_PrimaryKey()
    {
        var warnings = GovernanceEngine.Lint(
            [
                new TableDefinition
                {
                    Id = "sales.stg.order",
                    Database = "sales",
                    Schema = "stg",
                    Description = "Imported from SQL Server table stg.order",
                    Owner = new OwnerDefinition { Team = "Platform" },
                    Columns =
                    [
                        new ColumnDefinition
                        {
                            Name = "OrderId",
                            Type = "bigint",
                            Pk = false,
                            Description = "Imported from SQL Server column"
                        }
                    ]
                }
            ]).ToList();

        Assert.Contains(warnings, x => x.Contains("auto-generated description"));
        Assert.Contains(warnings, x => x.Contains("has no primary key"));
        Assert.Contains(warnings, x => x.Contains("Column 'sales.stg.order.OrderId' is using an auto-generated description"));
    }

    [Fact]
    public void Lint_Uses_Configurable_Policy_For_Enable_And_Severity()
    {
        var policy = new GovernancePolicy
        {
            MissingOwnerTeam = new GovernanceRulePolicy { Enabled = false, Severity = "warn" },
            MissingColumnDescription = new GovernanceRulePolicy { Enabled = true, Severity = "error" },
            MissingPrimaryKey = new GovernanceRulePolicy { Enabled = true, Severity = "warn" },
            ShortTableDescription = new GovernanceRulePolicy { Enabled = false, Severity = "warn", MinLength = 15 },
            AutoGeneratedTableDescription = new GovernanceRulePolicy { Enabled = false, Severity = "warn" },
            AutoGeneratedColumnDescription = new GovernanceRulePolicy { Enabled = false, Severity = "warn" }
        };

        var warnings = GovernanceEngine.Lint(
            [
                new TableDefinition
                {
                    Id = "sales.order",
                    Database = "sales",
                    Schema = "dbo",
                    Description = "short",
                    Owner = new OwnerDefinition { Team = "" },
                    Columns = [new ColumnDefinition { Name = "OrderId", Type = "bigint", Description = "", Pk = false }]
                }
            ],
            policy).ToList();

        Assert.DoesNotContain(warnings, w => w.Contains("Missing owner team"));
        Assert.Contains(warnings, w => w.StartsWith("ERROR:") && w.Contains("Missing description for column"));
        Assert.Contains(warnings, w => w.StartsWith("WARN:") && w.Contains("has no primary key"));
    }

    [Fact]
    public void GovernancePolicyLoader_Loads_File_From_Catalog_Governance_Path()
    {
        var root = Path.Combine(Path.GetTempPath(), "gitcatalog-tests", Guid.NewGuid().ToString("N"));
        var policyPath = Path.Combine(root, "catalog", "governance");
        Directory.CreateDirectory(policyPath);
        File.WriteAllText(
            Path.Combine(policyPath, "policy.yaml"),
            """
            missingOwnerTeam:
              enabled: false
              severity: info
            missingColumnDescription:
              enabled: true
              severity: error
            """);

        var result = GovernancePolicyLoader.Load(root);

        Assert.Empty(result.Diagnostics);
        Assert.False(result.Policy.MissingOwnerTeam.Enabled);
        Assert.Equal("error", result.Policy.MissingColumnDescription.Severity);
    }

    [Fact]
    public void GenerateEr_Emits_Entities_And_Relationships()
    {
        var er = MermaidGenerator.GenerateEr(
            [
                new TableDefinition
                {
                    Id = "sales.order",
                    Columns =
                    [
                        new ColumnDefinition { Name = "OrderId", Type = "bigint", Pk = true },
                        new ColumnDefinition { Name = "CustomerId", Type = "bigint", Fk = "sales.customer.CustomerId" }
                    ]
                },
                new TableDefinition
                {
                    Id = "sales.customer",
                    Columns = [new ColumnDefinition { Name = "CustomerId", Type = "bigint", Pk = true }]
                }
            ]);

        Assert.Contains("erDiagram", er);
        Assert.Contains("sales_order", er);
        Assert.Contains("bigint OrderId PK", er);
        Assert.Contains("sales_order }o--|| sales_customer : CustomerId", er);
    }

    [Fact]
    public void GenerateCatalogDocs_Emits_Index_And_Table_Page()
    {
        var docs = MarkdownGenerator.GenerateCatalogDocs(
            [
                new TableDefinition
                {
                    Id = "sales.order",
                    Database = "sales",
                    Schema = "dbo",
                    Description = "Customer order table",
                    Owner = new OwnerDefinition { Team = "Commercial Systems" },
                    Columns =
                    [
                        new ColumnDefinition
                        {
                            Name = "OrderId",
                            Type = "bigint",
                            Pk = true,
                            Description = "Primary key"
                        }
                    ]
                }
            ],
            ["WARN: Missing owner team on table 'sales.customer'."]);

        var index = docs.Single(d => d.RelativePath == "index.md").Content;
        var tablePage = docs.Single(d => d.RelativePath == "tables/sales.order.md").Content;

        Assert.Contains("# GitCatalog Generated Documentation", index);
        Assert.Contains("[sales.order](tables/sales.order.md)", index);
        Assert.Contains("Governance Findings", index);
        Assert.Contains("# sales.order", tablePage);
        Assert.Contains("| Name | Type | PK | FK | Description |", tablePage);
        Assert.Contains("| OrderId | bigint | Yes |  | Primary key |", tablePage);
    }

    [Fact]
    public void GenerateSiteAssets_Emits_Manifest_And_App_Files()
    {
        var assets = StaticSiteGenerator.GenerateSiteAssets(
            [
                new TableDefinition { Id = "sales.order" },
                new TableDefinition { Id = "sales.customer" }
            ]);

        Assert.Contains(assets, a => a.RelativePath == "index.html");
        Assert.Contains(assets, a => a.RelativePath == "app.css");
        Assert.Contains(assets, a => a.RelativePath == "app.js");

        var manifest = assets.Single(a => a.RelativePath == "manifest.json").Content;
        Assert.Contains("\"generatedRoot\": \"../generated\"", manifest);
        Assert.Contains("\"sales.customer\"", manifest);
        Assert.Contains("\"sales.order\"", manifest);
    }

    [Fact]
    public void SqlImporter_BuildTables_Maps_Primary_And_Foreign_Keys()
    {
        var importer = new SqlServerImporter();

        var tables = new[]
        {
            new SqlTableRow("sales", "dbo", "order"),
            new SqlTableRow("sales", "dbo", "customer")
        };

        var columns = new[]
        {
            new SqlColumnRow("dbo", "order", "OrderId", "bigint", 1, true),
            new SqlColumnRow("dbo", "order", "CustomerId", "bigint", 2, false),
            new SqlColumnRow("dbo", "customer", "CustomerId", "bigint", 1, true)
        };

        var foreignKeys = new[]
        {
            new SqlForeignKeyRow("dbo", "order", "CustomerId", "dbo", "customer", "CustomerId")
        };

        var mapped = importer.BuildTables(tables, columns, foreignKeys);

        Assert.Equal(2, mapped.Count);
        var order = mapped.Single(t => t.Id == "sales.order");
        Assert.Equal("sales", order.Database);
        Assert.Equal("dbo", order.Schema);
        Assert.Contains(order.Columns, c => c.Name == "OrderId" && c.Pk);
        Assert.Contains(order.Columns, c => c.Name == "CustomerId" && c.Fk == "sales.customer.CustomerId");
    }

    [Fact]
    public void SqlImporter_BuildTables_Uses_Schema_In_Id_For_NonDbo_Tables()
    {
        var importer = new SqlServerImporter();

        var tables = new[]
        {
            new SqlTableRow("sales", "stg", "order")
        };

        var columns = new[]
        {
            new SqlColumnRow("stg", "order", "OrderId", "bigint", 1, true)
        };

        var mapped = importer.BuildTables(tables, columns, []);

        var table = Assert.Single(mapped);
        Assert.Equal("sales.stg.order", table.Id);
    }

    [Fact]
    public void SqlImporter_MergeWithExisting_Preserves_Table_And_Column_Metadata()
    {
        var importer = new SqlServerImporter();

        var imported = new TableDefinition
        {
            Id = "sales.order",
            Database = "sales",
            Schema = "dbo",
            Description = "Imported from SQL Server table dbo.order",
            Owner = new OwnerDefinition { Team = "" },
            Columns =
            [
                new ColumnDefinition { Name = "OrderId", Type = "bigint", Pk = true, Description = "" },
                new ColumnDefinition { Name = "CustomerId", Type = "bigint", Fk = "sales.customer.CustomerId", Description = "" }
            ]
        };

        var existing = new TableDefinition
        {
            Id = "sales.order",
            Database = "sales",
            Schema = "dbo",
            Description = "Canonical order table for revenue reporting",
            Owner = new OwnerDefinition { Team = "Commercial Systems" },
            Columns =
            [
                new ColumnDefinition { Name = "OrderId", Type = "bigint", Pk = true, Description = "Stable business key" },
                new ColumnDefinition { Name = "CustomerId", Type = "bigint", Fk = "sales.customer.CustomerId", Description = "Joins to customer" }
            ]
        };

        var merged = importer.MergeWithExisting(imported, existing);

        Assert.Equal("Canonical order table for revenue reporting", merged.Description);
        Assert.Equal("Commercial Systems", merged.Owner.Team);
        Assert.Contains(merged.Columns, c => c.Name == "OrderId" && c.Description == "Stable business key");
        Assert.Contains(merged.Columns, c => c.Name == "CustomerId" && c.Description == "Joins to customer");
    }

    [Fact]
    public void SqlImporter_MergeWithExisting_Uses_Imported_Metadata_When_Existing_Is_Empty()
    {
        var importer = new SqlServerImporter();

        var imported = new TableDefinition
        {
            Id = "sales.customer",
            Database = "sales",
            Schema = "dbo",
            Description = "Imported from SQL Server table dbo.customer",
            Owner = new OwnerDefinition { Team = "Data Engineering" },
            Columns =
            [
                new ColumnDefinition { Name = "CustomerId", Type = "bigint", Pk = true, Description = "Generated identifier" }
            ]
        };

        var existing = new TableDefinition
        {
            Id = "sales.customer",
            Database = "sales",
            Schema = "dbo",
            Description = "",
            Owner = new OwnerDefinition { Team = "" },
            Columns = [new ColumnDefinition { Name = "CustomerId", Type = "bigint", Pk = true, Description = "" }]
        };

        var merged = importer.MergeWithExisting(imported, existing);

        Assert.Equal("Imported from SQL Server table dbo.customer", merged.Description);
        Assert.Equal("Data Engineering", merged.Owner.Team);
        Assert.Contains(merged.Columns, c => c.Name == "CustomerId" && c.Description == "Generated identifier");
    }

    [Fact]
    public void SqlImporter_BuildImportPlan_Classifies_Create_Update_Unchanged_And_Remove()
    {
        var importer = new SqlServerImporter();
        var root = Path.Combine(Path.GetTempPath(), "gitcatalog-tests", Guid.NewGuid().ToString("N"));
        var tablesPath = Path.Combine(root, "catalog", "tables");
        Directory.CreateDirectory(tablesPath);

        File.WriteAllText(
            Path.Combine(tablesPath, "sales.order.yaml"),
            """
            id: sales.order
            database: sales
            schema: dbo
            description: Canonical order table
            owner:
              team: Commercial Systems
            columns:
              - name: OrderId
                type: bigint
                pk: true
                description: Primary key
            """);

        File.WriteAllText(
            Path.Combine(tablesPath, "sales.legacy.yaml"),
            """
            id: sales.legacy
            database: sales
            schema: dbo
            description: Legacy table
            owner:
              team: Legacy
            columns:
              - name: LegacyId
                type: bigint
                pk: true
                description: Legacy key
            """);

        var imported = new List<TableDefinition>
        {
            new()
            {
                Id = "sales.customer",
                Database = "sales",
                Schema = "dbo",
                Description = "Imported from SQL Server table dbo.customer",
                Owner = new OwnerDefinition(),
                Columns = [new ColumnDefinition { Name = "CustomerId", Type = "bigint", Pk = true, Description = "" }]
            },
            new()
            {
                Id = "sales.order",
                Database = "sales",
                Schema = "dbo",
                Description = "Imported from SQL Server table dbo.order",
                Owner = new OwnerDefinition(),
                Columns = [new ColumnDefinition { Name = "OrderId", Type = "int", Pk = true, Description = "" }]
            }
        };

        var plan = importer.BuildImportPlan(imported, root);

        Assert.Contains(plan.Changes, c => c.TableId == "sales.customer" && c.Kind == ImportChangeKind.Create);
        Assert.Contains(plan.Changes, c => c.TableId == "sales.order" && c.Kind == ImportChangeKind.Update);
        Assert.Contains(plan.Changes, c => c.TableId == "sales.legacy" && c.Kind == ImportChangeKind.Remove);
        Assert.Equal(2, plan.Writes.Count);

        var update = Assert.Single(plan.Changes, c => c.TableId == "sales.order");
        Assert.Contains(update.DriftDetails, d => d.Contains("Column type changed: OrderId bigint -> int"));

        var create = Assert.Single(plan.Changes, c => c.TableId == "sales.customer");
        Assert.Contains(create.DriftDetails, d => d.Contains("file will be created", StringComparison.OrdinalIgnoreCase));

        var remove = Assert.Single(plan.Changes, c => c.TableId == "sales.legacy");
        Assert.Contains(remove.DriftDetails, d => d.Contains("absent from source schema", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void SqlImporter_BuildImportPlan_Does_Not_Write_Files()
    {
        var importer = new SqlServerImporter();
        var root = Path.Combine(Path.GetTempPath(), "gitcatalog-tests", Guid.NewGuid().ToString("N"));
        var tablesPath = Path.Combine(root, "catalog", "tables");
        Directory.CreateDirectory(tablesPath);

        var imported = new List<TableDefinition>
        {
            new()
            {
                Id = "sales.preview",
                Database = "sales",
                Schema = "dbo",
                Description = "Imported from SQL Server table dbo.preview",
                Owner = new OwnerDefinition(),
                Columns = [new ColumnDefinition { Name = "PreviewId", Type = "bigint", Pk = true, Description = "" }]
            }
        };

        var plan = importer.BuildImportPlan(imported, root);
        Assert.Contains(plan.Changes, c => c.TableId == "sales.preview" && c.Kind == ImportChangeKind.Create);
        var change = Assert.Single(plan.Changes);
        Assert.NotEmpty(change.DriftDetails);
        Assert.False(File.Exists(Path.Combine(tablesPath, "sales.preview.yaml")));
    }

    [Fact]
    public void SqlImporter_BuildImportPlan_Does_Not_Create_Tables_Directory_When_Missing()
    {
        var importer = new SqlServerImporter();
        var root = Path.Combine(Path.GetTempPath(), "gitcatalog-tests", Guid.NewGuid().ToString("N"));
        var tablesPath = Path.Combine(root, "catalog", "tables");

        var imported = new List<TableDefinition>
        {
            new()
            {
                Id = "sales.preview",
                Database = "sales",
                Schema = "dbo",
                Description = "Imported from SQL Server table dbo.preview",
                Owner = new OwnerDefinition(),
                Columns = [new ColumnDefinition { Name = "PreviewId", Type = "bigint", Pk = true, Description = "" }]
            }
        };

        var plan = importer.BuildImportPlan(imported, root);

        Assert.Single(plan.Writes);
        Assert.False(Directory.Exists(tablesPath));
    }

    private static string CreateTempRepoWithCatalog(string fileName, string yaml)
    {
        var root = Path.Combine(Path.GetTempPath(), "gitcatalog-tests", Guid.NewGuid().ToString("N"));
        var tablesPath = Path.Combine(root, "catalog", "tables");
        Directory.CreateDirectory(tablesPath);
        File.WriteAllText(Path.Combine(tablesPath, fileName), yaml);
        return root;
    }
}
