
using GitCatalog.Core;

namespace GitCatalog.Governance;

public static class GovernanceEngine
{
    public static IEnumerable<string> Lint(IEnumerable<TableDefinition> tables, GovernancePolicy? policy = null)
        => LintFindings(tables, policy).Select(f => f.ToString());

    public static IEnumerable<GovernanceFinding> LintFindings(IEnumerable<TableDefinition> tables, GovernancePolicy? policy = null)
    {
        policy ??= GovernancePolicy.CreateDefault();

        foreach (var table in tables)
        {
            if (policy.MissingOwnerTeam.Enabled && string.IsNullOrWhiteSpace(table.Owner.Team))
            {
                yield return Finding(policy.MissingOwnerTeam, "missing-owner-team", $"Missing owner team on table '{table.Id}'.");
            }

            if (policy.ShortTableDescription.Enabled
                && !string.IsNullOrWhiteSpace(table.Description)
                && table.Description.Length < policy.ShortTableDescription.MinLength)
            {
                yield return Finding(policy.ShortTableDescription, "short-table-description", $"Description is too short on table '{table.Id}'.");
            }

            if (policy.AutoGeneratedTableDescription.Enabled
                && table.Description.StartsWith("Imported from SQL Server table ", StringComparison.OrdinalIgnoreCase))
            {
                yield return Finding(
                    policy.AutoGeneratedTableDescription,
                    "auto-generated-table-description",
                    $"Table '{table.Id}' is using an auto-generated description; replace with business context.");
            }

            if (policy.MissingPrimaryKey.Enabled && !table.Columns.Any(c => c.Pk))
            {
                yield return Finding(policy.MissingPrimaryKey, "missing-primary-key", $"Table '{table.Id}' has no primary key column marked.");
            }

            foreach (var column in table.Columns)
            {
                if (policy.MissingColumnDescription.Enabled && string.IsNullOrWhiteSpace(column.Description))
                {
                    yield return Finding(
                        policy.MissingColumnDescription,
                        "missing-column-description",
                        $"Missing description for column '{table.Id}.{column.Name}'.");
                }
                else if (policy.AutoGeneratedColumnDescription.Enabled
                    && column.Description.StartsWith("Imported from SQL Server", StringComparison.OrdinalIgnoreCase))
                {
                    yield return Finding(
                        policy.AutoGeneratedColumnDescription,
                        "auto-generated-column-description",
                        $"Column '{table.Id}.{column.Name}' is using an auto-generated description; replace with business context.");
                }
            }
        }
    }

    public static IEnumerable<string> LintGraph(CatalogGraph graph)
        => LintGraphFindings(graph).Select(f => f.ToString());

    public static IEnumerable<GovernanceFinding> LintGraphFindings(CatalogGraph graph)
    {
        foreach (var entity in graph.Entities)
        {
            if ((entity.Type is CatalogEntityType.System or CatalogEntityType.Pipeline or CatalogEntityType.Dataset)
                && string.IsNullOrWhiteSpace(entity.Owner.Team))
            {
                yield return new GovernanceFinding(
                    GovernanceSeverity.Warn,
                    "graph-missing-owner",
                    $"Graph entity '{entity.Id}' ({entity.Type}) is missing owner team.");
            }

            if (entity.Type == CatalogEntityType.Dataset && string.IsNullOrWhiteSpace(entity.Classification))
            {
                yield return new GovernanceFinding(
                    GovernanceSeverity.Warn,
                    "graph-missing-classification",
                    $"Graph dataset '{entity.Id}' is missing data classification.");
            }

            if (entity.Type == CatalogEntityType.ExternalVendor && string.IsNullOrWhiteSpace(entity.Boundary))
            {
                yield return new GovernanceFinding(
                    GovernanceSeverity.Warn,
                    "graph-missing-boundary",
                    $"Graph external vendor '{entity.Id}' is missing boundary metadata.");
            }
        }

        var entityById = graph.Entities.ToDictionary(e => e.Id, StringComparer.OrdinalIgnoreCase);
        foreach (var rel in graph.Relationships)
        {
            if (string.Equals(rel.Criticality, "high", StringComparison.OrdinalIgnoreCase)
                && string.IsNullOrWhiteSpace(rel.Technology))
            {
                yield return new GovernanceFinding(
                    GovernanceSeverity.Warn,
                    "graph-critical-rel-missing-tech",
                    $"Critical relationship '{rel.Id}' is missing technology metadata.");
            }

            var touchesConsumer =
                (entityById.TryGetValue(rel.From, out var source) && source.Type == CatalogEntityType.Consumer)
                || (entityById.TryGetValue(rel.To, out var target) && target.Type == CatalogEntityType.Consumer);

            if (touchesConsumer && string.IsNullOrWhiteSpace(rel.Description))
            {
                yield return new GovernanceFinding(
                    GovernanceSeverity.Warn,
                    "graph-consumer-rel-missing-description",
                    $"Consumer-facing relationship '{rel.Id}' is missing description.");
            }
        }
    }

    private static GovernanceFinding Finding(GovernanceRulePolicy rule, string code, string message)
        => new(ParseSeverity(rule.Severity), code, message);

    private static GovernanceSeverity ParseSeverity(string? severity)
    {
        if (string.IsNullOrWhiteSpace(severity))
        {
            return GovernanceSeverity.Warn;
        }

        return severity.Trim().ToLowerInvariant() switch
        {
            "info" => GovernanceSeverity.Info,
            "error" => GovernanceSeverity.Error,
            _ => GovernanceSeverity.Warn
        };
    }
}

public enum GovernanceSeverity
{
    Info,
    Warn,
    Error
}

public sealed record GovernanceFinding(GovernanceSeverity Severity, string Code, string Message)
{
    public override string ToString() => $"{Severity.ToString().ToUpperInvariant()}: {Message}";
}
