using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace GitCatalog.Governance;

public sealed class GovernancePolicy
{
    public GovernanceRulePolicy MissingOwnerTeam { get; set; } = new();
    public GovernanceRulePolicy ShortTableDescription { get; set; } = new() { MinLength = 15 };
    public GovernanceRulePolicy AutoGeneratedTableDescription { get; set; } = new();
    public GovernanceRulePolicy MissingPrimaryKey { get; set; } = new();
    public GovernanceRulePolicy MissingColumnDescription { get; set; } = new();
    public GovernanceRulePolicy AutoGeneratedColumnDescription { get; set; } = new();

    public static GovernancePolicy CreateDefault() => new();
}

public sealed class GovernanceRulePolicy
{
    public bool Enabled { get; set; } = true;
    public string Severity { get; set; } = "warn";
    public int MinLength { get; set; }
}

public static class GovernancePolicyLoader
{
    public static GovernancePolicyLoadResult Load(string repoRoot)
    {
        var policyPath = Path.Combine(repoRoot, "catalog", "governance", "policy.yaml");
        if (!File.Exists(policyPath))
        {
            return new GovernancePolicyLoadResult(GovernancePolicy.CreateDefault(), []);
        }

        var deserializer = new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();

        try
        {
            var text = File.ReadAllText(policyPath);
            var policy = deserializer.Deserialize<GovernancePolicy>(text) ?? GovernancePolicy.CreateDefault();
            EnsureDefaults(policy);
            return new GovernancePolicyLoadResult(policy, []);
        }
        catch (Exception ex)
        {
            return new GovernancePolicyLoadResult(
                GovernancePolicy.CreateDefault(),
                [$"Failed to parse governance policy at {policyPath}: {ex.Message}"]);
        }
    }

    private static void EnsureDefaults(GovernancePolicy policy)
    {
        policy.MissingOwnerTeam ??= new GovernanceRulePolicy();
        policy.ShortTableDescription ??= new GovernanceRulePolicy { MinLength = 15 };
        policy.AutoGeneratedTableDescription ??= new GovernanceRulePolicy();
        policy.MissingPrimaryKey ??= new GovernanceRulePolicy();
        policy.MissingColumnDescription ??= new GovernanceRulePolicy();
        policy.AutoGeneratedColumnDescription ??= new GovernanceRulePolicy();

        if (policy.ShortTableDescription.MinLength <= 0)
        {
            policy.ShortTableDescription.MinLength = 15;
        }
    }
}

public sealed record GovernancePolicyLoadResult(GovernancePolicy Policy, IReadOnlyList<string> Diagnostics);
