
using GitCatalog.Core;

namespace GitCatalog.Governance;

public static class GovernanceEngine
{
    public static IEnumerable<string> Lint(IEnumerable<TableDefinition> tables, GovernancePolicy? policy = null)
        => LintFindings(tables, policy).Select(f => f.ToString());

    public static IEnumerable<GovernanceFinding> LintFindings(IEnumerable<TableDefinition> tables, GovernancePolicy? policy = null)
    {
        policy ??= GovernancePolicy.CreateDefault();

        foreach (var table in tables)
        {
            if (policy.MissingOwnerTeam.Enabled && string.IsNullOrWhiteSpace(table.Owner.Team))
            {
                yield return Finding(policy.MissingOwnerTeam, "missing-owner-team", $"Missing owner team on table '{table.Id}'.");
            }

            if (policy.ShortTableDescription.Enabled
                && !string.IsNullOrWhiteSpace(table.Description)
                && table.Description.Length < policy.ShortTableDescription.MinLength)
            {
                yield return Finding(policy.ShortTableDescription, "short-table-description", $"Description is too short on table '{table.Id}'.");
            }

            if (policy.AutoGeneratedTableDescription.Enabled
                && table.Description.StartsWith("Imported from SQL Server table ", StringComparison.OrdinalIgnoreCase))
            {
                yield return Finding(
                    policy.AutoGeneratedTableDescription,
                    "auto-generated-table-description",
                    $"Table '{table.Id}' is using an auto-generated description; replace with business context.");
            }

            if (policy.MissingPrimaryKey.Enabled && !table.Columns.Any(c => c.Pk))
            {
                yield return Finding(policy.MissingPrimaryKey, "missing-primary-key", $"Table '{table.Id}' has no primary key column marked.");
            }

            foreach (var column in table.Columns)
            {
                if (policy.MissingColumnDescription.Enabled && string.IsNullOrWhiteSpace(column.Description))
                {
                    yield return Finding(
                        policy.MissingColumnDescription,
                        "missing-column-description",
                        $"Missing description for column '{table.Id}.{column.Name}'.");
                }
                else if (policy.AutoGeneratedColumnDescription.Enabled
                    && column.Description.StartsWith("Imported from SQL Server", StringComparison.OrdinalIgnoreCase))
                {
                    yield return Finding(
                        policy.AutoGeneratedColumnDescription,
                        "auto-generated-column-description",
                        $"Column '{table.Id}.{column.Name}' is using an auto-generated description; replace with business context.");
                }
            }
        }
    }

    private static GovernanceFinding Finding(GovernanceRulePolicy rule, string code, string message)
        => new(ParseSeverity(rule.Severity), code, message);

    private static GovernanceSeverity ParseSeverity(string? severity)
    {
        if (string.IsNullOrWhiteSpace(severity))
        {
            return GovernanceSeverity.Warn;
        }

        return severity.Trim().ToLowerInvariant() switch
        {
            "info" => GovernanceSeverity.Info,
            "error" => GovernanceSeverity.Error,
            _ => GovernanceSeverity.Warn
        };
    }
}

public enum GovernanceSeverity
{
    Info,
    Warn,
    Error
}

public sealed record GovernanceFinding(GovernanceSeverity Severity, string Code, string Message)
{
    public override string ToString() => $"{Severity.ToString().ToUpperInvariant()}: {Message}";
}
